### ISSUE TITLE
Set IP address on TestResponse objects

### ISSUE THREAD

**Issue by ryanfox** [Pylons/webtest#118]
In a Pyramid app, I am getting the remote user's IP address via `request.remote_addr`.  Googling yields next to nothing, but I've figured out it is currently possible to spoof the remote IP address on a TestRequest via something like the following:

```
request = TestRequest.blank('/')
request.remote_addr = '127.0.0.1'
```

But this information gets wiped out after the first request/response cycle.  It would be nice to be able to specify something like

```
self.app.post('/form', {'field1': value1, 'field2': value2}, remote_addr='127.0.0.1')
```

or even have `remote_addr` persist across more than 1 request.  Would that be feasible?

**Comment by romuald** [comment]
FYI Typo in the initial comment that I blindly copypasted, the key is indeed `REMOTE_ADDR`
