### ISSUE TITLE
Assertion error should be raised when you have non-string response header

### ISSUE THREAD

**Issue by fangpenlin** [Pylons/webtest#119]
``` python
from __future__ import unicode_literals
import unittest
from wsgiref.simple_server import make_server

from webtest import TestApp
from pyramid.config import Configurator
from pyramid.response import Response


def hello_world(request):
    return Response("{'foo': 'bar'}", content_type='application/json')

def main():
    config = Configurator()
    config.add_route('hello', '/')
    config.add_view(hello_world, route_name='hello')
    app = config.make_wsgi_app()
    return app


class TestAppCase(unittest.TestCase):

    def test_unicode_header_should_raise_error(self):
        app = main()
        test_app = TestApp(app)
        test_app.get('/', status=500)


if __name__ == '__main__':
    app = main()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

here is a demo, when you run the app like this

```
python demo.py
```

Then visit that server

```
curl localhost:8080
```

then you get a traceback like this

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/.env/lib/python2.7/site-packages/pyramid/router.py", line 243, in __call__
    return response(request.environ, start_response)
  File "/.env/lib/python2.7/site-packages/webob/response.py", line 1021, in __call__
    start_response(self.status, headerlist)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 180, in start_response
    assert type(val) is StringType,"Header values must be strings"
AssertionError: Header values must be strings
```

since the `content_type` we give there

```
content_type='application/json'
```

is an unicode. However, when you run the tests

```
nosetests -sv demo.py
```

you got

```
AppError: Bad response: 200 OK (not 500)
```

It doesn't raise an assertion. I think this is pretty bad, I always need to run my application in real environment so that I know I have unicode passed to the response. Instead of deferring error spotting to production environment, I suggest we should check the response value, see is there unicode in header.

**Comment by bjmc** [comment]
:+1: For this suggestion. I've just been caught out by changes that passed fine in WebTest, but failed when deployed and run with uWSGI.

**Comment by bertjwregeer** [comment]
This would be a WebOb issue, since it doesn't coerce the `content_type` to a `str()` in `webob.response.Response`, and instead just sets it directly into the headers.

However I would argue that the user is setting:

`from __future__ import unicode_literals`

Means they have to take extra care that they provide the right arguments to any libraries and coerce types themselves:

```
Sterling:~ xistence$ python2.7
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> type('application/json')
<type 'str'>
>>> 
Sterling:~ xistence$ ~/.pyenv/versions/3.6.1/bin/python
Python 3.6.1 (default, Apr  3 2017, 20:13:48) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> type('test')
<class 'str'>
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
Sterling:~ xistence$ python2.7
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import unicode_literals
>>> type('application/json')
<type 'unicode'>
>>> 
```

My suggestion, drop the `unicode_literals` from your code, and use `u'your string'` as appropriate instead, I as the WebOb maintainer am loathe to try and add more shims to make a future import work correctly.

----

Adding a check in webtest for this when running on Py2 would be great too.

**Comment by bjmc** [comment]
> Adding a check in webtest for this when running on Py2

Is basically the only thing I'm asking for. My understanding is that the WSGI spec requires HTTP headers to be "native strings" (in both Py2 and Py3) and uWSGI correctly enforces that requirement. WebTest does not.

It's frustrating to have code that passes all tests in both Python 2 and Python 3, and then blows up when deployed to a live (pre-production, thankfully) stack.
