### ISSUE TITLE
Support for WebSocket

### ISSUE THREAD

**Issue by foxx** [Pylons/webtest#137]
I'm currently looking at extending webtest to support a WebSocket client. 

The cleanest implementation seems to be following the same pattern as `TestApp` and `StopableWSGIServer`, using the [websockets](https://github.com/aaugustin/websockets) library. The WS library mentioned is only `3.x` compatible, there are `2.x` compatible libraries such as `ws4py` but they do not perform as well, although admittedly if it's a test server then performance doesn't matter too much.

I'm more than happy to contribute my code back into this project, would such a PR be accepted?

**Comment by gawel** [comment]
I'm not against that. But I really think that the best option is to create a separate package (like django-webtest or webtest_selenium). We made some effort in the past to keep the code as small as possible.

If you need to change things in webtest itself for that, PR with tests are always welcome.

Once it's done you'll be able to add a link to your package in webtest's doc to promote this great addition if you want to.

**Comment by foxx** [comment]
Sure that works, I'll close this issue for now and re-open when it's done, thanks for the quick reply :)
