### ISSUE TITLE
Classifiers and testenv for Python 3.4

### ISSUE THREAD

**Issue by mdomke** [Pylons/webtest#139]
Currently there are only classifiers set for Python 3.2 and 3.3 in the `setup.py`. Also there are only a test-environments for those versions. Actually the tests seem to work fine under Python 3.4, so that I think it would be good idea to declare the package Python 3.4 compliant.

**Comment by gawel** [comment]
done

**Comment by mdomke** [comment]
Ok, great. I was making a pull-request myself and was looking for a solution to keep the Python 3.2 support, but if it's ok to drop it I'm fine with it…
