### ISSUE TITLE
Add license headers to source files.

### ISSUE THREAD

**Issue by anniesullie** [Pylons/webtest#141]
Some chromium dependencies import this project and would require the presence of valid license headers in all source files.

**Comment by mmerickel** [comment]
This is the same request as https://github.com/Pylons/webob/issues/211 opened against webob. The Pylons repositories all follow the same format (all 80+ repos). Every repo has a `license.txt` at the root and I don't think we're about to switch every single repo to accommodate chromium's development/release processes.
