### ISSUE TITLE
2.0.19 has a 'none-any' wheel which is Python >= 2.7

### ISSUE THREAD

**Issue by tseaver** [Pylons/webtest#143]
Python 2.6 support requires `ordereddict`.

Pyramid [tests fail on 2.6](https://travis-ci.org/Pylons/pyramid/jobs/88959628) because of that wheel.

**Comment by tseaver** [comment]
The pragmatic fix is just to remove the wheel.  If recent versions of pip support [PEP 496](https://www.python.org/dev/peps/pep-0496/), we might be able to use `ordereddict; python_version < '2.7'`.

**Comment by gawel** [comment]
I've made a release just to add this wheel (see #142)...
.whl removed from pypi.
Sorry for that.

**Comment by tseaver** [comment]
No apology needed.  I wish the wheelies had gotten the story more solid before beginning to hype the format.

**Comment by stevepiercy** [comment]
@tseaver I learned something new about understanding the stack trace, thanks to you looking into this. Both `master` and `1.6-branch` pass on TravisCI now. https://travis-ci.org/Pylons/pyramid/branches
