### ISSUE TITLE
Allow Bearer Authorization Headers

### ISSUE THREAD

**Issue by coolnay309** [Pylons/webtest#153]
Allow "Bearer <token>" authorization header to support access_token based auth

**Comment by coolnay309** [comment]
like below:

git diff --git a/webtest/app.py b/webtest/app.py
index 8110ed8..a0da8cf 100644
--- a/webtest/app.py
+++ b/webtest/app.py
@@ -204,6 +204,8 @@ class TestApp(object):
                     val = ':'.join(list(val))
                     val = b64encode(to_bytes(val)).strip()
                     val = val.decode('latin1')
+                elif authtype == 'Bearer' and val and isinstance(val, (str, unicode)):
+                    val = val.strip()
                 else:
                     raise ValueError(invalid_value)
                 value = str('%s %s' % (authtype, val))

**Comment by coolnay309** [comment]
Pull Request open. Thanks!

**Comment by wichert** [comment]
I am guessing this is for JWT-style backends? A fair number of those use `JWT` instead of `Bearer` as auth type, so perhaps that should be added as well.

**Comment by merwok** [comment]
OAuth also uses bearer tokens.

**Comment by gawel** [comment]
This was added https://github.com/Pylons/webtest/blob/78b79377cb5d40d7945ba172c6800a73cabd6868/CHANGELOG.rst#2021-2016-04-12

**Comment by wichert** [comment]
@gawel That fix is incomplete: it does not support the `JWT` scheme which is just as common as `Bearer` for JWT tokens.

**Comment by gawel** [comment]
This is not really the original topic :)

Can you add an example ?

**Comment by wichert** [comment]
You added support for a header like `Authorization: Bearer <token>`. For JWT that header can also look like `Authorization: JWT <token>`. So the simplest fix is to treat `JWT` just like `Bearer`. Perhaps a more flexible approach would be to expose both the auth scheme (Basic/Bearer/JTW/etc.) and the auth value so you don't have to hardcode this type of knowledge.
