### ISSUE TITLE
All encoding hints from server are ignored, leading to invalid charset handling

### ISSUE THREAD

**Issue by wichert** [Pylons/webtest#160]
I had a very interesting debugging session yesterday. I have a pyramid application which generated this HTML content:

```html
<!DOCTYPE html>
<html lang="nl-nl">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="content-type" />
</head>

<body>
    <form accept-charset="UTF-8" action="http://www.acme.com/settings" method="POST" name="personalForm">
        <span>Tést</span>
        <input id="firstname" name="firstname" placeholder="" type="text" value="Jané" />
        <span>Tést</span>
        <span>Tést</span>
    </form>
</body>
</html>
```

Trying to parse that with WebTest results in an incorrect value for the input value:

```python
# vim: fileencoding=utf-8
from webtest import TestResponse

with open('input.html', 'rb') as input:
    r = TestResponse(input.read())
value = r.forms[0].get('firstname').value

print u'%s read from %s: %r' % (u'Good' if value == u'Jané' else u'BAD', fn, value)
```

As soon as you add another copy of the `<span>Tést</span>` (or add any other non-ASCII character anywhere) the input value is decoded correctly.

I eventually traced this down to how decoding is done: even though the HTML file explicitly says it uses UTF-8, and there is a `Content-Type': text/html; charset=UTF-8` header WebTest (via bs4) tries to guess the decoding. And if you have ccharset installed it happens to guess wrong in this example.

I believe that if there are both a Content-Type headers and a content-type meta tag guessing should never happen since it is likely to produce errors, and obviously is not what the server is intending.

**Comment by gawel** [comment]
Can you check if my commit fix your problem ?

It only take care of the Content-Type header (response.charset). It's the easiest fix.

**Comment by wichert** [comment]
That commit fixes it!

**Comment by gawel** [comment]
Cool. New release is available.

**Comment by href** [comment]
Ever since this was implemented I get the following warnings when running my tests:

`UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.`

In my case those warnings seem to stem from the forms module:
https://github.com/Pylons/webtest/blob/9ca03a04927744fbea1b6a3fd209623981204bf1/webtest/forms.py#L400

I run my tests on Python 3, so it might not occur in Python 2.
