### ISSUE TITLE
Decoding issue for non-ASCII characters in JSON response

### ISSUE THREAD

**Issue by merwok** [Pylons/webtest#177]
django-rest-framework doesn’t escape basic unicode characters in its JSON rendering, but also doesn’t include a charset parameter in the Content-Type (following the IANA registration document).  In webtest, the response.json property calls json.loads(self.testbody), and the self.testbody property doesn’t try to decode if there is no charset param.  A test with ``assert resp.json == {'name': 'Île-de-France'}`` fails because the UTF-8 bytes are replaced with ``��``.

**Comment by bertjwregeer** [comment]
JSON is defined as being UTF-8/UTF-16/UTF-32, there is no charset for JSON. So not including a charset content-type parameter is correct.

Implementations are encouraged to use UTF-8 only.

**Comment by merwok** [comment]
Yes, this is why I did not reopen the drf issue :)  The problem here is that webtest defaults to ascii (with replace error handler) rather than UTF-8.

**Comment by merwok** [comment]
Thanks @gawel for the fix and release!  Works fine.  :sparkles: :space_invader: :artificial_satellite: :baguette_bread:
