### ISSUE TITLE
Add RELEASING.txt

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/webtest#178]
Pyramid has a very detailed [RELEASING.txt](https://github.com/Pylons/pyramid/blob/master/RELEASING.txt) file that documents its release process.

It would be nice to at least announce releases to https://groups.google.com/forum/#!forum/pylons-discuss and Twitter via `@PylonsProject`. Usually Michael Merickel sends emails, and I send the tweets. @gawel any project maintainer should be able to send tweets on behalf of `@PylonsProject`, and I can grant that access through TweetDeck. Please let me know.

**Comment by gawel** [comment]
I'm using zest.releaser so the release process take no time and is clean.

I probably can send a mail to the list but I have problems to send mails with my email client. As I remember I'm rejected (it works with the web UI but I'd like to avoid that)

Can you check my account on the pylons-discuss mailing list ? I'm gael at gawel.org

I'm not using TweetDeck. I'll give it a try and let you know.

**Comment by gawel** [comment]
I have a really basic config/usage of zest.releaser.

Here is my config (in ~/.pypirc):

```
[zest.releaser]
no-input = true
create-wheel = yes
```
Then after a ```pip install "zest.releaser[recommended]"``` you'll be able to use the ```fullrelease``` script

**Comment by gawel** [comment]
Just successfully sent an email to the list \o/ I don't know why it always failed in the past.

Also I've just tried tweetdeck. Seems nice. I'm gawel_ on twitter if you want to add me to the Pylons Team

Feel free to close this issue when it's done

**Comment by stevepiercy** [comment]
@gawel you should have received a notification to confirm and accept that you wish to become a member. Please let me know when you complete the process, and then this can be closed.

Thanks for the docs, too!

**Comment by gawel** [comment]
All good. Thanks
