### ISSUE TITLE
subdomain request

### ISSUE THREAD

**Issue by truonghoangnguyen** [Pylons/webtest#184]
I want to request from subdomain for example
`self.testapp.get('A.localhost.com/')` or `self.testapp.get('B.localhost.com/')`

**Comment by mmerickel** [comment]
You can probably do something like `headers={'Host': 'A.localhost.com'}`.

**Comment by truonghoangnguyen** [comment]
Thanks @mmerickel , I success by enter full address in request
`response = self.testapp.get('http://a.localhost/login')`
