### ISSUE TITLE
Python 3.7 DeprecationWarning for collections.abc

### ISSUE THREAD

**Issue by gamikun** [Pylons/webtest#196]
This warning is showing

`webtest/lint.py:201: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working.`

I looked at Python docs and says **collections.abc** was added in version 3.3. I guess a condition could be added to **lint.py**, when >= 3.3 import collections.abc, otherwise import collections.

[](https://docs.python.org/3.4/library/collections.abc.html)

> New in version 3.3: Formerly, this module was part of the collections module.

**Comment by stevepiercy** [comment]
Before changing the linter, we should fix the code. Potential fix in [pytest](https://github.com/pytest-dev/pytest/pull/3497/files).

Note Python 3.8 final is [scheduled for release on 2019-10-20](https://www.python.org/dev/peps/pep-0569/). Two months later, [Python 2.7 is EOLed on 2020-01-01](https://www.python.org/dev/peps/pep-0373/). Alternatively, we could drop support for 2.7 sooner than its EOL, and avoid a check.

**Comment by mgedmin** [comment]
Do you have any plans for a new release with this fix?

(Can I help make it happen?)

**Comment by gawel** [comment]
You can. Check https://github.com/Pylons/webtest/blob/master/RELEASING.rst

Else I'll try to push a release this week-end.
