### ISSUE TITLE
Add WebTest to wiki.python.org

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/webtest#197]
This came across my Twitter feed today from pytest:
https://wiki.python.org/moin/PythonTestingToolsTaxonomy#Web_Testing_Tools

I assume that the following entry should go under that heading, but I'd like a quick review before I submit the change.

Tool | Category | Author | Part of | Claim to fame
-- | -- | -- | -- | --
[WebTest](https://docs.pylonsproject.org/projects/webtest/en/latest/) | Browser simulation | [Gael Pasgrimaud](https://github.com/gawel) | [Pylons Project](https://pylonsproject.org/) | Test your web applications without starting an HTTP server, and without poking into the web framework shortcutting pieces of your application that need to be tested. The tests WebTest runs are entirely equivalent to how a WSGI HTTP server would call an application.

**Comment by gawel** [comment]
Thats ok for me. Thanks!

**Comment by stevepiercy** [comment]
Done!
https://wiki.python.org/moin/PythonTestingToolsTaxonomy#Web_Testing_Tools
