### ISSUE TITLE
Default value for button and submit is wrong

### ISSUE THREAD

**Issue by bdauvergne** [Pylons/webtest#205]
webtest give a default value of None to submit and button but it should be the empty string.

With normal x-www-form-urlencoded multipart/form it just produces the pair "<button-name>=None" which is ugly and false, but works most of the time, but if you have a file upload then encode_multipart is called before utils.encode_params() (encode_params() is responsible for serializable None as the 'None' string) it raises a ValueError because encode_multipart() expect only string like values.

**Comment by gawel** [comment]
I guess it's an easy fix. Can you provide a PR?

**Comment by bdauvergne** [comment]
Yep, hope it's ok for you.

**Comment by gawel** [comment]
That was fast! Merged. Thanks.

**Comment by bdauvergne** [comment]
When do you think 2.0.31 could be released ? This fix currently blocks our tests. If I can help on something.

**Comment by bdauvergne** [comment]
Great, thank your.
