### ISSUE TITLE
urllib.parse.splithost() is deprecated as of 3.8

### ISSUE THREAD

**Issue by nedvedikd** [Pylons/webtest#217]
As of Python 3.8 the splithost function is deprecated as stated [here](https://github.com/python/cpython/blob/1d2862a323ae1387e306942253b1e487018e2b7f/Lib/urllib/parse.py#L995).

`splithost()` is being used in this repo in [response.py on line 88](https://github.com/Pylons/webtest/blob/c87c61b57e452f21fe4604ed1f5c9dfe8e7a250f/webtest/response.py#L88).

**Comment by toolness** [comment]
Thanks for reporting this! Similarly, [`splittype` is deprecated here](https://github.com/python/cpython/blob/1d2862a323ae1387e306942253b1e487018e2b7f/Lib/urllib/parse.py#L974) and is being used in this repo in [response.py on line 87](https://github.com/Pylons/webtest/blob/c87c61b57e452f21fe4604ed1f5c9dfe8e7a250f/webtest/response.py#L87).

**Comment by Tenzer** [comment]
https://github.com/Pylons/webtest/pull/222 should hopefully fix this. It turns out the functions doesn't actually have any effect so could be removed.
