### ISSUE TITLE
Is there any way to open a popup form when click?

### ISSUE THREAD

**Issue by thoongnv** [Pylons/webtest#233]
```
<button type="submit" class="stripe-button-el" style="visibility: visible;">
    <span style="display: block; min-height: 30px;">Open popup form</span>
</button>
```

In the UI, when click the above button Stripe checkout will build the form, I fill and submit it after that?

As I see the current `webtest`, `click`, `clickbutton` behavior (in `webtest/response.py`) will go to a URL so is there any way to open a popup form?

**Comment by stevepiercy** [comment]
It looks like the answer is that webtest does not do what you want. See https://docs.pylonsproject.org/projects/webtest/en/latest/api.html#webtest.response.TestResponse.click and https://docs.pylonsproject.org/projects/webtest/en/latest/api.html#webtest.response.TestResponse.clickbutton.

I think that Selenium will do what you want, but even that is tricky for this situation.

**Comment by thoongnv** [comment]
thanks @stevepiercy, let me check this with Selenium
